data = {'ADO': {'Code': 'ADO',
         'Country': 'Andorra',
         'HDI': '37',
         'GNI': '13'},
 'AFG': {'Code': 'AFG',
         'Country': 'Afghanistan',
         'HDI': '174',
         'GNI': '167'},
 'AGO': {'Code': 'AGO',
         'Country': 'Angola',
         'HDI': '164',
         'GNI': '111'},
 'ALB': {'Code': 'ALB',
         'Country': 'Albania',
         'HDI': '75',
         'GNI': '94'},
 'ARE': {'Code': 'ARE',
         'Country': 'United Arab Emirates',
         'HDI': '43',
         'GNI': '4'},
 'ARG': {'Code': 'ARG',
         'Country': 'Argentina',
         'HDI': '60',
         'GNI': '59'},
 'ARM': {'Code': 'ARM',
         'Country': 'Armenia',
         'HDI': '81',
         'GNI': '100'},
 'ATG': {'Code': 'ATG',
         'Country': 'Antigua and Barbuda',
         'HDI': '16',
         'GNI': '45'},
 'AUS': {'Code': 'AUS',
         'Country': 'Australia',
         'HDI': '2',
         'GNI': '18'},
 'AUT': {'Code': 'AUT',
         'Country': 'Austria',
         'HDI': '28',
         'GNI': '19'},
 'AZE': {'Code': 'AZE',
         'Country': 'Azerbaijan',
         'HDI': '85',
         'GNI': '96'},
 'BDI': {'Code': 'BDI',
         'Country': 'Burundi',
         'HDI': '184',
         'GNI': '184'},
 'BEL': {'Code': 'BEL',
         'Country': 'Belgium',
         'HDI': '18',
         'GNI': '25'},
 'BEN': {'Code': 'BEN',
         'Country': 'Benin',
         'HDI': '154',
         'GNI': '157'},
 'BFA': {'Code': 'BFA',
         'Country': 'Burkina Faso',
         'HDI': '180',
         'GNI': '165'},
 'BGD': {'Code': 'BGD',
         'Country': 'Bangladesh',
         'HDI': '147',
         'GNI': '158'},
 'BGR': {'Code': 'BGR',
         'Country': 'Bulgaria',
         'HDI': '68',
         'GNI': '73'},
 'BHS': {'Code': 'BHS',
         'Country': 'Bahamas The',
         'HDI': '53',
         'GNI': '32'},
 'BIH': {'Code': 'BIH',
         'Country': 'Bosnia and Herzegovina',
         'HDI': '79',
         'GNI': '84'},
 'BLR': {'Code': 'BLR',
         'Country': 'Belarus',
         'HDI': '72',
         'GNI': '70'},
 'BLZ': {'Code': 'BLZ',
         'Country': 'Belize',
         'HDI': '84',
         'GNI': '99'},
 'BOL': {'Code': 'BOL',
         'Country': 'Bolivia',
         'HDI': '109',
         'GNI': '118'},
 'BRA': {'Code': 'BRA',
         'Country': 'Brazil',
         'HDI': '88',
         'GNI': '75'},
 'BRB': {'Code': 'BRB',
         'Country': 'Barbados',
         'HDI': '49',
         'GNI': '41'},
 'BRN': {'Code': 'BRN',
         'Country': 'Brunei Darussalam',
         'HDI': '44',
         'GNI': '7'},
 'BTN': {'Code': 'BTN',
         'Country': 'Bhutan',
         'HDI': '110',
         'GNI': '115'},
 'BWA': {'Code': 'BWA',
         'Country': 'Botswana',
         'HDI': '113',
         'GNI': '61'},
 'CAF': {'Code': 'CAF',
         'Country': 'Central African Republic',
         'HDI': '176',
         'GNI': '178'},
 'CAN': {'Code': 'CAN',
         'Country': 'Canada',
         'HDI': '8',
         'GNI': '14'},
 'CHE': {'Code': 'CHE',
         'Country': 'Switzerland',
         'HDI': '13',
         'GNI': '10'},
 'CHL': {'Code': 'CHL',
         'Country': 'Chile',
         'HDI': '55',
         'GNI': '63'},
 'CHN': {'Code': 'CHN',
         'Country': 'China',
         'HDI': '105',
         'GNI': '102'},
 'CIV': {'Code': 'CIV',
         'Country': "Cote d'Ivoire",
         'HDI': '165',
         'GNI': '154'},
 'CMR': {'Code': 'CMR',
         'Country': 'Cameroon',
         'HDI': '148',
         'GNI': '141'},
 'COG': {'Code': 'COG',
         'Country': 'Congo Rep.',
         'HDI': '186',
         'GNI': '185'},
 'COL': {'Code': 'COL',
         'Country': 'Colombia',
         'HDI': '92',
         'GNI': '81'},
 'COM': {'Code': 'COM',
         'Country': 'Comoros',
         'HDI': '151',
         'GNI': '162'},
 'CPV': {'Code': 'CPV',
         'Country': 'Cape Verde',
         'HDI': '132',
         'GNI': '128'},
 'CRI': {'Code': 'CRI',
         'Country': 'Costa Rica',
         'HDI': '73',
         'GNI': '72'},
 'CUB': {'Code': 'CUB',
         'Country': 'Cuba',
         'HDI': '21',
         'GNI': '116'},
 'CYP': {'Code': 'CYP',
         'Country': 'Cyprus',
         'HDI': '45',
         'GNI': '37'},
 'CZE': {'Code': 'CZE',
         'Country': 'Czech Republic',
         'HDI': '32',
         'GNI': '39'},
 'DEU': {'Code': 'DEU',
         'Country': 'Germany',
         'HDI': '11',
         'GNI': '24'},
 'DJI': {'Code': 'DJI',
         'Country': 'Djibouti',
         'HDI': '163',
         'GNI': '140'},
 'DMA': {'Code': 'DMA',
         'Country': 'Dominica',
         'HDI': '39',
         'GNI': '83'},
 'DNK': {'Code': 'DNK',
         'Country': 'Denmark',
         'HDI': '19',
         'GNI': '16'},
 'DOM': {'Code': 'DOM',
         'Country': 'Dominican Republic',
         'HDI': '101',
         'GNI': '88'},
 'DZA': {'Code': 'DZA',
         'Country': 'Algeria',
         'HDI': '98',
         'GNI': '85'},
 'ECU': {'Code': 'ECU',
         'Country': 'Ecuador',
         'HDI': '89',
         'GNI': '91'},
 'EGY': {'Code': 'EGY',
         'Country': 'Egypt Arab Rep.',
         'HDI': '115',
         'GNI': '104'},
 'ERI': {'Code': 'ERI',
         'Country': 'Eritrea',
         'HDI': '143',
         'GNI': '181'},
 'ESP': {'Code': 'ESP',
         'Country': 'Spain',
         'HDI': '24',
         'GNI': '28'},
 'EST': {'Code': 'EST',
         'Country': 'Estonia',
         'HDI': '38',
         'GNI': '44'},
 'ETH': {'Code': 'ETH',
         'Country': 'Ethiopia',
         'HDI': '175',
         'GNI': '175'},
 'FIN': {'Code': 'FIN',
         'Country': 'Finland',
         'HDI': '14',
         'GNI': '20'},
 'FJI': {'Code': 'FJI',
         'Country': 'Fiji',
         'HDI': '97',
         'GNI': '114'},
 'FRA': {'Code': 'FRA',
         'Country': 'France',
         'HDI': '20',
         'GNI': '26'},
 'FSM': {'Code': 'FSM',
         'Country': 'Micronesia Fed. Sts.',
         'HDI': '112',
         'GNI': '124'},
 'GAB': {'Code': 'GAB',
         'Country': 'Gabon',
         'HDI': '106',
         'GNI': '60'},
 'GBR': {'Code': 'GBR',
         'Country': 'United Kingdom',
         'HDI': '31',
         'GNI': '21'},
 'GEO': {'Code': 'GEO',
         'Country': 'Georgia',
         'HDI': '80',
         'GNI': '107'},
 'GHA': {'Code': 'GHA',
         'Country': 'Ghana',
         'HDI': '145',
         'GNI': '159'},
 'GIN': {'Code': 'GIN',
         'Country': 'Guinea',
         'HDI': '173',
         'GNI': '172'},
 'GMB': {'Code': 'GMB',
         'Country': 'Gambia The',
         'HDI': '168',
         'GNI': '160'},
 'GNB': {'Code': 'GNB',
         'Country': 'Guinea-Bissau',
         'HDI': '181',
         'GNI': '183'},
 'GNQ': {'Code': 'GNQ',
         'Country': 'Equatorial Guinea',
         'HDI': '133',
         'GNI': '49'},
 'GRC': {'Code': 'GRC',
         'Country': 'Greece',
         'HDI': '27',
         'GNI': '29'},
 'GRD': {'Code': 'GRD',
         'Country': 'Grenada',
         'HDI': '40',
         'GNI': '82'},
 'GTM': {'Code': 'GTM',
         'Country': 'Guatemala',
         'HDI': '131',
         'GNI': '108'},
 'GUY': {'Code': 'GUY',
         'Country': 'Guyana',
         'HDI': '118',
         'GNI': '131'},
 'HKG': {'Code': 'HKG',
         'Country': 'Hong Kong SAR China',
         'HDI': '25',
         'GNI': '11'},
 'HND': {'Code': 'HND',
         'Country': 'Honduras',
         'HDI': '117',
         'GNI': '121'},
 'HRV': {'Code': 'HRV',
         'Country': 'Croatia',
         'HDI': '61',
         'GNI': '48'},
 'HTI': {'Code': 'HTI',
         'Country': 'Haiti',
         'HDI': '160',
         'GNI': '170'},
 'HUN': {'Code': 'HUN',
         'Country': 'Hungary',
         'HDI': '46',
         'GNI': '47'},
 'IDN': {'Code': 'IDN',
         'Country': 'Indonesia',
         'HDI': '125',
         'GNI': '125'},
 'IND': {'Code': 'IND',
         'Country': 'India',
         'HDI': '135',
         'GNI': '132'},
 'IRL': {'Code': 'IRL',
         'Country': 'Ireland',
         'HDI': '5',
         'GNI': '17'},
 'IRN': {'Code': 'IRN',
         'Country': 'Iran Islamic Rep.',
         'HDI': '90',
         'GNI': '69'},
 'IRQ': {'Code': 'IRQ',
         'Country': 'Iraq',
         'HDI': '123',
         'GNI': '145'},
 'ISL': {'Code': 'ISL',
         'Country': 'Iceland',
         'HDI': '6',
         'GNI': '22'},
 'ISR': {'Code': 'ISR',
         'Country': 'Israel',
         'HDI': '15',
         'GNI': '30'},
 'ITA': {'Code': 'ITA',
         'Country': 'Italy',
         'HDI': '26',
         'GNI': '27'},
 'JAM': {'Code': 'JAM',
         'Country': 'Jamaica',
         'HDI': '91',
         'GNI': '89'},
 'JOR': {'Code': 'JOR',
         'Country': 'Jordan',
         'HDI': '95',
         'GNI': '103'},
 'JPN': {'Code': 'JPN',
         'Country': 'Japan',
         'HDI': '12',
         'GNI': '23'},
 'KAZ': {'Code': 'KAZ',
         'Country': 'Kazakhstan',
         'HDI': '77',
         'GNI': '76'},
 'KEN': {'Code': 'KEN',
         'Country': 'Kenya',
         'HDI': '146',
         'GNI': '155'},
 'KGZ': {'Code': 'KGZ',
         'Country': 'Kyrgyz Republic',
         'HDI': '121',
         'GNI': '143'},
 'KHM': {'Code': 'KHM',
         'Country': 'Cambodia',
         'HDI': '137',
         'GNI': '150'},
 'KIR': {'Code': 'KIR',
         'Country': 'Kiribati',
         'HDI': '134',
         'GNI': '123'},
 'KNA': {'Code': 'KNA',
         'Country': 'St. Kitts and Nevis',
         'HDI': '33',
         'GNI': '55'},
 'KOR': {'Code': 'KOR',
         'Country': 'Korea Rep.',
         'HDI': '17',
         'GNI': '31'},
 'KWT': {'Code': 'KWT',
         'Country': 'Kuwait',
         'HDI': '58',
         'GNI': '6'},
 'LAO': {'Code': 'LAO',
         'Country': 'Lao PDR',
         'HDI': '141',
         'GNI': '144'},
 'LBN': {'Code': 'LBN',
         'Country': 'Lebanon',
         'HDI': '47',
         'GNI': '68'},
 'LBR': {'Code': 'LBR',
         'Country': 'Liberia',
         'HDI': '182',
         'GNI': '186'},
 'LBY': {'Code': 'LBY',
         'Country': 'Libya',
         'HDI': '65',
         'GNI': '51'},
 'LCA': {'Code': 'LCA',
         'Country': 'St. Lucia',
         'HDI': '36',
         'GNI': '78'},
 'LIE': {'Code': 'LIE',
         'Country': 'Liechtenstein',
         'HDI': '10',
         'GNI': '1'},
 'LKA': {'Code': 'LKA',
         'Country': 'Sri Lanka',
         'HDI': '102',
         'GNI': '113'},
 'LSO': {'Code': 'LSO',
         'Country': 'Lesotho',
         'HDI': '156',
         'GNI': '147'},
 'LTU': {'Code': 'LTU',
         'Country': 'Lithuania',
         'HDI': '50',
         'GNI': '52'},
 'LUX': {'Code': 'LUX',
         'Country': 'Luxembourg',
         'HDI': '22',
         'GNI': '3'},
 'LVA': {'Code': 'LVA',
         'Country': 'Latvia',
         'HDI': '54',
         'GNI': '50'},
 'MAR': {'Code': 'MAR',
         'Country': 'Morocco',
         'HDI': '130',
         'GNI': '117'},
 'MDA': {'Code': 'MDA',
         'Country': 'Moldova',
         'HDI': '111',
         'GNI': '129'},
 'MDG': {'Code': 'MDG',
         'Country': 'Madagascar',
         'HDI': '150',
         'GNI': '171'},
 'MDV': {'Code': 'MDV',
         'Country': 'Maldives',
         'HDI': '122',
         'GNI': '105'},
 'MEX': {'Code': 'MEX',
         'Country': 'Mexico',
         'HDI': '64',
         'GNI': '56'},
 'MHL': {'Code': 'MHL',
         'Country': 'Marshall Islands',
         'HDI': '127',
         'GNI': '130'},
 'MKD': {'Code': 'MKD',
         'Country': 'Macedonia FYR',
         'HDI': '86',
         'GNI': '79'},
 'MLI': {'Code': 'MLI',
         'Country': 'Mali',
         'HDI': '178',
         'GNI': '161'},
 'MLT': {'Code': 'MLT',
         'Country': 'Malta',
         'HDI': '42',
         'GNI': '42'},
 'MMR': {'Code': 'MMR',
         'Country': 'Myanmar',
         'HDI': '149',
         'GNI': '156'},
 'MNE': {'Code': 'MNE',
         'Country': 'Montenegro',
         'HDI': '59',
         'GNI': '64'},
 'MNG': {'Code': 'MNG',
         'Country': 'Mongolia',
         'HDI': '114',
         'GNI': '126'},
 'MOZ': {'Code': 'MOZ',
         'Country': 'Mozambique',
         'HDI': '183',
         'GNI': '179'},
 'MRT': {'Code': 'MRT',
         'Country': 'Mauritania',
         'HDI': '152',
         'GNI': '142'},
 'MUS': {'Code': 'MUS',
         'Country': 'Mauritius',
         'HDI': '82',
         'GNI': '66'},
 'MWI': {'Code': 'MWI',
         'Country': 'Malawi',
         'HDI': '172',
         'GNI': '176'},
 'MYS': {'Code': 'MYS',
         'Country': 'Malaysia',
         'HDI': '69',
         'GNI': '57'},
 'NAM': {'Code': 'NAM',
         'Country': 'Namibia',
         'HDI': '119',
         'GNI': '98'},
 'NER': {'Code': 'NER',
         'Country': 'Niger',
         'HDI': '185',
         'GNI': '180'},
 'NGA': {'Code': 'NGA',
         'Country': 'Nigeria',
         'HDI': '158',
         'GNI': '148'},
 'NIC': {'Code': 'NIC',
         'Country': 'Nicaragua',
         'HDI': '128',
         'GNI': '135'},
 'NLD': {'Code': 'NLD',
         'Country': 'Netherlands',
         'HDI': '7',
         'GNI': '12'},
 'NOR': {'Code': 'NOR',
         'Country': 'Norway',
         'HDI': '1',
         'GNI': '5'},
 'NPL': {'Code': 'NPL',
         'Country': 'Nepal',
         'HDI': '159',
         'GNI': '168'},
 'NZL': {'Code': 'NZL',
         'Country': 'New Zealand',
         'HDI': '3',
         'GNI': '34'},
 'OMN': {'Code': 'OMN',
         'Country': 'Oman',
         'HDI': '29',
         'GNI': '38'},
 'PAK': {'Code': 'PAK',
         'Country': 'Pakistan',
         'HDI': '139',
         'GNI': '133'},
 'PAN': {'Code': 'PAN',
         'Country': 'Panama',
         'HDI': '67',
         'GNI': '71'},
 'PER': {'Code': 'PER',
         'Country': 'Peru',
         'HDI': '78',
         'GNI': '92'},
 'PHL': {'Code': 'PHL',
         'Country': 'Philippines',
         'HDI': '108',
         'GNI': '120'},
 'PLW': {'Code': 'PLW',
         'Country': 'Palau',
         'HDI': '23',
         'GNI': '87'},
 'PNG': {'Code': 'PNG',
         'Country': 'Papua New Guinea',
         'HDI': '157',
         'GNI': '146'},
 'POL': {'Code': 'POL',
         'Country': 'Poland',
         'HDI': '52',
         'GNI': '54'},
 'PRT': {'Code': 'PRT',
         'Country': 'Portugal',
         'HDI': '51',
         'GNI': '40'},
 'PRY': {'Code': 'PRY',
         'Country': 'Paraguay',
         'HDI': '107',
         'GNI': '109'},
 'QAT': {'Code': 'QAT',
         'Country': 'Qatar',
         'HDI': '48',
         'GNI': '2'},
 'ROM': {'Code': 'ROM',
         'Country': 'Romania',
         'HDI': '62',
         'GNI': '65'},
 'RUS': {'Code': 'RUS',
         'Country': 'Russian Federation',
         'HDI': '76',
         'GNI': '53'},
 'RWA': {'Code': 'RWA',
         'Country': 'Rwanda',
         'HDI': '171',
         'GNI': '173'},
 'SAU': {'Code': 'SAU',
         'Country': 'Saudi Arabia',
         'HDI': '66',
         'GNI': '35'},
 'SDN': {'Code': 'SDN',
         'Country': 'Sudan',
         'HDI': '170',
         'GNI': '149'},
 'SEN': {'Code': 'SEN',
         'Country': 'Senegal',
         'HDI': '161',
         'GNI': '151'},
 'SGP': {'Code': 'SGP',
         'Country': 'Singapore',
         'HDI': '34',
         'GNI': '8'},
 'SLB': {'Code': 'SLB',
         'Country': 'Solomon Islands',
         'HDI': '136',
         'GNI': '139'},
 'SLE': {'Code': 'SLE',
         'Country': 'Sierra Leone',
         'HDI': '177',
         'GNI': '177'},
 'SLV': {'Code': 'SLV',
         'Country': 'El Salvador',
         'HDI': '99',
         'GNI': '97'},
 'SOM': {'Code': 'SOM',
         'Country': 'Somalia',
         'HDI': '166',
         'GNI': '182'},
 'SRB': {'Code': 'SRB',
         'Country': 'Serbia',
         'HDI': '70',
         'GNI': '74'},
 'STP': {'Code': 'STP',
         'Country': 'Sao Tome and Principe',
         'HDI': '140',
         'GNI': '152'},
 'SUR': {'Code': 'SUR',
         'Country': 'Suriname',
         'HDI': '103',
         'GNI': '93'},
 'SVK': {'Code': 'SVK',
         'Country': 'Slovak Republic',
         'HDI': '41',
         'GNI': '43'},
 'SVN': {'Code': 'SVN',
         'Country': 'Slovenia',
         'HDI': '35',
         'GNI': '33'},
 'SWE': {'Code': 'SWE',
         'Country': 'Sweden',
         'HDI': '9',
         'GNI': '15'},
 'SWZ': {'Code': 'SWZ',
         'Country': 'Swaziland',
         'HDI': '138',
         'GNI': '106'},
 'SYC': {'Code': 'SYC',
         'Country': 'Seychelles',
         'HDI': '30',
         'GNI': '46'},
 'SYR': {'Code': 'SYR',
         'Country': 'Syrian Arab Republic',
         'HDI': '124',
         'GNI': '112'},
 'TCD': {'Code': 'TCD',
         'Country': 'Chad',
         'HDI': '179',
         'GNI': '166'},
 'TGO': {'Code': 'TGO',
         'Country': 'Togo',
         'HDI': '155',
         'GNI': '174'},
 'THA': {'Code': 'THA',
         'Country': 'Thailand',
         'HDI': '104',
         'GNI': '86'},
 'TJK': {'Code': 'TJK',
         'Country': 'Tajikistan',
         'HDI': '126',
         'GNI': '153'},
 'TKM': {'Code': 'TKM',
         'Country': 'Turkmenistan',
         'HDI': '100',
         'GNI': '101'},
 'TMP': {'Code': 'TMP',
         'Country': 'Timor-Leste',
         'HDI': '144',
         'GNI': '127'},
 'TON': {'Code': 'TON',
         'Country': 'Tonga',
         'HDI': '94',
         'GNI': '119'},
 'TTO': {'Code': 'TTO',
         'Country': 'Trinidad and Tobago',
         'HDI': '71',
         'GNI': '36'},
 'TUN': {'Code': 'TUN',
         'Country': 'Tunisia',
         'HDI': '96',
         'GNI': '90'},
 'TUR': {'Code': 'TUR',
         'Country': 'Turkey',
         'HDI': '93',
         'GNI': '58'},
 'TZA': {'Code': 'TZA',
         'Country': 'Tanzania',
         'HDI': '167',
         'GNI': '163'},
 'UGA': {'Code': 'UGA',
         'Country': 'Uganda',
         'HDI': '162',
         'GNI': '169'},
 'UKR': {'Code': 'UKR',
         'Country': 'Ukraine',
         'HDI': '74',
         'GNI': '95'},
 'URY': {'Code': 'URY',
         'Country': 'Uruguay',
         'HDI': '63',
         'GNI': '67'},
 'USA': {'Code': 'USA',
         'Country': 'United States',
         'HDI': '4',
         'GNI': '9'},
 'UZB': {'Code': 'UZB',
         'Country': 'Uzbekistan',
         'HDI': '116',
         'GNI': '138'},
 'VCT': {'Code': 'VCT',
         'Country': 'St. Vincent and the Grenadines',
         'HDI': '56',
         'GNI': '80'},
 'VEN': {'Code': 'VEN',
         'Country': 'Venezuela RB',
         'HDI': '87',
         'GNI': '62'},
 'VNM': {'Code': 'VNM',
         'Country': 'Vietnam',
         'HDI': '129',
         'GNI': '134'},
 'VUT': {'Code': 'VUT',
         'Country': 'Vanuatu',
         'HDI': '83',
         'GNI': '122'},
 'WSM': {'Code': 'WSM',
         'Country': 'Samoa',
         'HDI': '57',
         'GNI': '110'},
 'YEM': {'Code': 'YEM',
         'Country': 'Yemen Rep.',
         'HDI': '153',
         'GNI': '137'},
 'ZAF': {'Code': 'ZAF',
         'Country': 'South Africa',
         'HDI': '120',
         'GNI': '77'},
 'ZAR': {'Code': 'ZAR',
         'Country': 'Congo Dem. Rep.',
         'HDI': '142',
         'GNI': '136'},
 'ZMB': {'Code': 'ZMB',
         'Country': 'Zambia',
         'HDI': '169',
         'GNI': '164'},
 'ZWE': {'Code': 'ZWE',
         'Country': 'Zimbabwe',
         'HDI': '187',
         'GNI': '187'}
}
